### ISSUE TITLE
Tabla de Riesgos 

### ISSUE THREAD

**Issue by gustavR0** [gadd-gj/documentacion-inegi#1]
:sparkles: **Tabla de Riesgos** :sparkles:

**Descripcion**
Documento (latex) con un tabla de plan de riesgos que visualizan en su proyecto se divide en dos tablas una llamada **Tabla de riesgos** y la otra en **Posibles Riesgos**

**Contenido**

1. **Tabla de riesgos columnas**
- [ ] Técnico
- [ ] Externo
- [ ] Organización
- [ ] Dirección del Proyecto

2. **Tabla Posibles Riesgos**
- [ ] Riesgo
- [ ] Tipo
- [ ] Descripción

**Comment by gadd-gj** [comment]
this issue closes #1
