### ISSUE TITLE
Vision y Alcance

### ISSUE THREAD

**Issue by gustavR0** [gadd-gj/documentacion-inegi#2]
:sparkles: **Vision y Alcance** :sparkles:

**Descripción**
Documento látex (Visión y alcance) del software en desarrollo

**Contenido**
- [ ] Puede tratar de un visor en mapas, gráficas, dashboard y analítica de una base de datos
real de al menos 1,000,000 de registros
- [ ]  Tema especificado: salud, netflix, spotify, juegos,
inegi, entre otros.

**Comment by gadd-gj** [comment]
This Issue closes #2

**Comment by gadd-gj** [comment]
this issue closes #2
