### ISSUE TITLE
Comunicación Efectiva en el Equipo

### ISSUE THREAD

**Issue by gustavR0** [gadd-gj/documentacion-inegi#3]
:sparkles: **Comunicación Efectiva en el Equipo** :sparkles:

**Descripción**
Documento (latex) con un plan de comunicacion efectiva entre los miembros del equipo

**Contenido**
- [x] Proponer formas de organizar la aportación de cada integrante
- [x] Proponer ideas para que los integrantes entiendan el proyecto
- [x] Proponer plataformas de comunicación para el equipo
- [x] Formas de fomentar la confianza entre los integrantes del equipo por cualquier problema que llegue a suceder

**Comment by gadd-gj** [comment]
This Issue closes #3

**Comment by gadd-gj** [comment]
This Issue closes #3
